root_dir:
    "/home/yixin/Desktop/github_repo/de_novo_miRNA"
miRBase_mature:
    "ftp://mirbase.org/pub/mirbase/22.1/mature.fa.gz"
miRBase_hairpin:
    "ftp://mirbase.org/pub/mirbase/22.1/hairpin.fa.gz"
